### ISSUE TITLE
classy-C4 not working with official PlantUML

### ISSUE THREAD

**Issue by anb0s** [plantuml/plantuml-stdlib#56] opened 2022-05-26 08:47 UTC
I've tried classy-C4 with official PlantUML server and it shows this [errors](https://www.plantuml.com/plantuml/uml/fPFDJeGm4CVlFCL8C432neid8sHNFHerwWjqoyHjChIRjcXuUrdO5gaXcyroce__pFmwfMjZcRPjGz63siAgWWq9Zd07EoHIqHfbtISdLGJzToKafxP6kEV4ZEbM_FQ6AscPaAYhHSaUjL5oEMywOx6fZZEIqOKI4ea_sSVWvKCkuOmeEmeAI0tQ5zPWsflFR8lK6yct4dLvRNMBMRvOzOI6Qx6tGib3yUjWCO9PFEZbyCRJEBotmPiD6WNdulcg2_7yVJZ2HnUOZVEoSpbzuGMeo-q-aU-a8lNL7RfDtedRs91W1if_kzGeQzHf7kucqFjuK1ByEYwv0FEEbFtbAI0OM40yx3Vk3R-ewOnn7hbtzmi0)

![image](https://user-images.githubusercontent.com/95811/170453235-3d9f7458-5cf5-4517-ba41-4522efd55f34.png)

**Comment by arnaudroques** [comment] 2022-05-26 09:01
Can you post your complete example?

```
@startuml
!include <DomainStory/domainStory>
Boundary(System) {
    Person(Alice)
    Conversation(weather)
    Person(Bob)
}
activity(1, Alice, talks about the, weather, with, Bob)
@enduml
```

[is working for us](http://www.plantuml.com/plantuml/uml/JSlHgi8m3CRn-pv5pjqAWuFt8dFw0CAU85i32xODjEcaYEzk6OBcwkD7_aDMJ5g2DtyS5rySmV4g0JbEAgd-k-y-cL5AT9XgDzMi52my3RIxKSeIkxFdXUmk5ubRGrHk_Y3KbPBz_HrbjkPbS57UM6jtw67FUr3qzmmuIr7GjS4dRuDrxM4l1ugk1Fy6).

Thanks!

**Comment by anb0s** [comment] 2022-05-26 09:18
I'm sorry i've copied the wrong link (from testing domainstory), now updated
```
@startuml
Bob -> Alice : hello


    !include <classy-c4/container>
    !include <classy-c4/person>
    !include <classy-c4/system>

    !$system = $new(System)
    $call($system, 'setName', 'Label', $void=%true())
    $call($system, 'setDescription', 'Optional Description', $void=%true())

    !$person = $new(Person)
    $call($person, 'setName', 'Label', $void=%true())
    $call($person, 'setDescription', 'Optional Description', $void=%true())

    !$container = $new(Container)
    $call($container, 'setName', 'Label', $void=%true())
    $call($container, 'setDescription', 'Optional Description', $void=%true())
    $call($container, 'setTechnology', 'Technology', $void=%true())

    !$personAlias = $call($person, 'render')
    !$containerAlias = $call($container, 'render')
    $call($system, 'render', $void=%true())

    Rel($personAlias, $containerAlias, "Label", "Optional Technology")
@enduml
```

**Comment by johnholliday** [comment] 2023-01-02 18:53
Any update? Having the same issue - cannot use Classy-C4.

**Comment by arnaudroques** [comment] 2023-01-04 14:19
> Any update? Having the same issue - cannot use Classy-C4.

I think the issue is on classy-c4 side, so you should open an issue here https://github.com/james-gadrow-kr/classy-c4

**Comment by The-Lum** [comment] 2024-05-23 19:21
FYI that is now fixed by:
- #105

Thanks @james-gadrow-kr

**Comment by The-Lum** [comment] 2024-10-20 10:16
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed.
- Thanks @anb0s  for the report;
- Thanks @james-gadrow-kr for the fix;
- Thanks PlantUML team for your work.

Regards.

**Closed by The-Lum** 2024-10-20 10:16 UTC
